title: BCCA Peoples Construction LTD
description: "Quality Landscaping & Construction Since 2009 - Serving Greater Vancouver"
url: "https://peoplesconstruction.github.io"
baseurl: ""

permalink: pretty

defaults:
  - scope:
      path: "en"
    values:
      lang: "en"
      lang_name: "English"
  - scope:
      path: "zh"
    values:
      lang: "zh"
      lang_name: "中文"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - docs/
  - .Rhistory
